// Package server provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"net/http"
	"strings"
)

// AWSUploadRequestOptions defines model for AWSUploadRequestOptions.
type AWSUploadRequestOptions struct {
	ShareWithAccounts []string `json:"share_with_accounts"`
}

// AWSUploadStatus defines model for AWSUploadStatus.
type AWSUploadStatus struct {
	Ami    string `json:"ami"`
	Region string `json:"region"`
}

// ArchitectureItem defines model for ArchitectureItem.
type ArchitectureItem struct {
	Arch       string   `json:"arch"`
	ImageTypes []string `json:"image_types"`
}

// Architectures defines model for Architectures.
type Architectures []ArchitectureItem

// AzureUploadRequestOptions defines model for AzureUploadRequestOptions.
type AzureUploadRequestOptions struct {

	// Name of the resource group where the image should be uploaded.
	ResourceGroup string `json:"resource_group"`

	// ID of subscription where the image should be uploaded.
	SubscriptionId string `json:"subscription_id"`

	// ID of the tenant where the image should be uploaded. This link explains how
	// to find it in the Azure Portal:
	// https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-to-find-tenant
	TenantId string `json:"tenant_id"`
}

// AzureUploadStatus defines model for AzureUploadStatus.
type AzureUploadStatus struct {
	ImageName string `json:"image_name"`
}

// ComposeRequest defines model for ComposeRequest.
type ComposeRequest struct {
	Customizations *Customizations `json:"customizations,omitempty"`
	Distribution   string          `json:"distribution"`
	ImageRequests  []ImageRequest  `json:"image_requests"`
}

// ComposeResponse defines model for ComposeResponse.
type ComposeResponse struct {
	Id string `json:"id"`
}

// ComposeStatus defines model for ComposeStatus.
type ComposeStatus struct {
	ImageStatus ImageStatus `json:"image_status"`
}

// ComposesResponse defines model for ComposesResponse.
type ComposesResponse struct {
	Data  []ComposesResponseItem `json:"data"`
	Links struct {
		First string `json:"first"`
		Last  string `json:"last"`
	} `json:"links"`
	Meta struct {
		Count int `json:"count"`
	} `json:"meta"`
}

// ComposesResponseItem defines model for ComposesResponseItem.
type ComposesResponseItem struct {
	CreatedAt string      `json:"created_at"`
	Id        string      `json:"id"`
	Request   interface{} `json:"request"`
}

// Customizations defines model for Customizations.
type Customizations struct {
	Packages     *[]string     `json:"packages,omitempty"`
	Subscription *Subscription `json:"subscription,omitempty"`
}

// DistributionItem defines model for DistributionItem.
type DistributionItem struct {
	Description string `json:"description"`
	Name        string `json:"name"`
}

// Distributions defines model for Distributions.
type Distributions []DistributionItem

// GCPUploadRequestOptions defines model for GCPUploadRequestOptions.
type GCPUploadRequestOptions struct {

	// List of valid Google accounts to share the imported Compute Node image with.
	// Each string must contain a specifier of the account type. Valid formats are:
	//   - 'user:{emailid}': An email address that represents a specific
	//     Google account. For example, 'alice@example.com'.
	//   - 'serviceAccount:{emailid}': An email address that represents a
	//     service account. For example, 'my-other-app@appspot.gserviceaccount.com'.
	//   - 'group:{emailid}': An email address that represents a Google group.
	//     For example, 'admins@example.com'.
	//   - 'domain:{domain}': The G Suite domain (primary) that represents all
	//     the users of that domain. For example, 'google.com' or 'example.com'.
	//     If not specified, the imported Compute Node image is not shared with any
	//     account.
	ShareWithAccounts []string `json:"share_with_accounts"`
}

// GCPUploadStatus defines model for GCPUploadStatus.
type GCPUploadStatus struct {
	ImageName string `json:"image_name"`
	ProjectId string `json:"project_id"`
}

// HTTPError defines model for HTTPError.
type HTTPError struct {
	Detail string `json:"detail"`
	Title  string `json:"title"`
}

// HTTPErrorList defines model for HTTPErrorList.
type HTTPErrorList struct {
	Errors []HTTPError `json:"errors"`
}

// ImageRequest defines model for ImageRequest.
type ImageRequest struct {
	Architecture  string        `json:"architecture"`
	ImageType     string        `json:"image_type"`
	UploadRequest UploadRequest `json:"upload_request"`
}

// ImageStatus defines model for ImageStatus.
type ImageStatus struct {
	Status       string        `json:"status"`
	UploadStatus *UploadStatus `json:"upload_status,omitempty"`
}

// Package defines model for Package.
type Package struct {
	Name    string `json:"name"`
	Summary string `json:"summary"`
	Version string `json:"version"`
}

// PackagesResponse defines model for PackagesResponse.
type PackagesResponse struct {
	Data  []Package `json:"data"`
	Links struct {
		First string `json:"first"`
		Last  string `json:"last"`
	} `json:"links"`
	Meta struct {
		Count int `json:"count"`
	} `json:"meta"`
}

// Readiness defines model for Readiness.
type Readiness struct {
	Readiness string `json:"readiness"`
}

// Subscription defines model for Subscription.
type Subscription struct {
	ActivationKey string `json:"activation-key"`
	BaseUrl       string `json:"base-url"`
	Insights      bool   `json:"insights"`
	Organization  int    `json:"organization"`
	ServerUrl     string `json:"server-url"`
}

// UploadRequest defines model for UploadRequest.
type UploadRequest struct {
	Options interface{} `json:"options"`
	Type    UploadTypes `json:"type"`
}

// UploadStatus defines model for UploadStatus.
type UploadStatus struct {
	Options interface{} `json:"options"`
	Status  string      `json:"status"`
	Type    UploadTypes `json:"type"`
}

// UploadTypes defines model for UploadTypes.
type UploadTypes string

// List of UploadTypes
const (
	UploadTypes_aws   UploadTypes = "aws"
	UploadTypes_azure UploadTypes = "azure"
	UploadTypes_gcp   UploadTypes = "gcp"
)

// Version defines model for Version.
type Version struct {
	Version string `json:"version"`
}

// ComposeImageJSONBody defines parameters for ComposeImage.
type ComposeImageJSONBody ComposeRequest

// GetComposesParams defines parameters for GetComposes.
type GetComposesParams struct {

	// max amount of composes, default 100
	Limit *int `json:"limit,omitempty"`

	// composes page offset, default 0
	Offset *int `json:"offset,omitempty"`
}

// GetPackagesParams defines parameters for GetPackages.
type GetPackagesParams struct {

	// distribution to look up packages for
	Distribution string `json:"distribution"`

	// architecture to look up packages for
	Architecture string `json:"architecture"`

	// packages to look for
	Search string `json:"search"`

	// max amount of packages, default 100
	Limit *int `json:"limit,omitempty"`

	// packages page offset, default 0
	Offset *int `json:"offset,omitempty"`
}

// ComposeImageRequestBody defines body for ComposeImage for application/json ContentType.
type ComposeImageJSONRequestBody ComposeImageJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// get the architectures and their image types available for a given distribution
	// (GET /architectures/{distribution})
	GetArchitectures(ctx echo.Context, distribution string) error
	// compose image
	// (POST /compose)
	ComposeImage(ctx echo.Context) error
	// get a collection of previous compose requests for the logged in user
	// (GET /composes)
	GetComposes(ctx echo.Context, params GetComposesParams) error
	// get status of an image compose
	// (GET /composes/{composeId})
	GetComposeStatus(ctx echo.Context, composeId string) error
	// get the available distributions
	// (GET /distributions)
	GetDistributions(ctx echo.Context) error
	// get the openapi json specification
	// (GET /openapi.json)
	GetOpenapiJson(ctx echo.Context) error

	// (GET /packages)
	GetPackages(ctx echo.Context, params GetPackagesParams) error
	// return the readiness
	// (GET /ready)
	GetReadiness(ctx echo.Context) error
	// get the service version
	// (GET /version)
	GetVersion(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetArchitectures converts echo context to params.
func (w *ServerInterfaceWrapper) GetArchitectures(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "distribution" -------------
	var distribution string

	err = runtime.BindStyledParameter("simple", false, "distribution", ctx.Param("distribution"), &distribution)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter distribution: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetArchitectures(ctx, distribution)
	return err
}

// ComposeImage converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeImage(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeImage(ctx)
	return err
}

// GetComposes converts echo context to params.
func (w *ServerInterfaceWrapper) GetComposes(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetComposesParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetComposes(ctx, params)
	return err
}

// GetComposeStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GetComposeStatus(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "composeId" -------------
	var composeId string

	err = runtime.BindStyledParameter("simple", false, "composeId", ctx.Param("composeId"), &composeId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter composeId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetComposeStatus(ctx, composeId)
	return err
}

// GetDistributions converts echo context to params.
func (w *ServerInterfaceWrapper) GetDistributions(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetDistributions(ctx)
	return err
}

// GetOpenapiJson converts echo context to params.
func (w *ServerInterfaceWrapper) GetOpenapiJson(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetOpenapiJson(ctx)
	return err
}

// GetPackages converts echo context to params.
func (w *ServerInterfaceWrapper) GetPackages(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPackagesParams
	// ------------- Required query parameter "distribution" -------------

	err = runtime.BindQueryParameter("form", true, true, "distribution", ctx.QueryParams(), &params.Distribution)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter distribution: %s", err))
	}

	// ------------- Required query parameter "architecture" -------------

	err = runtime.BindQueryParameter("form", true, true, "architecture", ctx.QueryParams(), &params.Architecture)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter architecture: %s", err))
	}

	// ------------- Required query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, true, "search", ctx.QueryParams(), &params.Search)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter search: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetPackages(ctx, params)
	return err
}

// GetReadiness converts echo context to params.
func (w *ServerInterfaceWrapper) GetReadiness(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetReadiness(ctx)
	return err
}

// GetVersion converts echo context to params.
func (w *ServerInterfaceWrapper) GetVersion(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetVersion(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET("/architectures/:distribution", wrapper.GetArchitectures)
	router.POST("/compose", wrapper.ComposeImage)
	router.GET("/composes", wrapper.GetComposes)
	router.GET("/composes/:composeId", wrapper.GetComposeStatus)
	router.GET("/distributions", wrapper.GetDistributions)
	router.GET("/openapi.json", wrapper.GetOpenapiJson)
	router.GET("/packages", wrapper.GetPackages)
	router.GET("/ready", wrapper.GetReadiness)
	router.GET("/version", wrapper.GetVersion)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9Rae2/bOBL/KoTugO4CkizbedXA4rbX7XVzKHaLJLf3RxMEtDi2uJVIlaTiegN/9wNJ",
	"vUXZzjYBbv+qI5Izv3lwXuyjF/Ms5wyYkt7i0ZNxAhk2P9/89/o/ecoxuYIvBUj1a64oZ2YpFzwHoSjY",
	"MwkWcL+hKrnHccyLkhR8xVmegrf45E1n85PTs/OL19F05t35HlWQmT1qm4O38KQSlK29nV99wELgrbfb",
	"+Z6ALwUVQDQZF6O7+gxf/g6x0kRq5NcKq8KBGGe0g1B/CKL4Yh6dv56fn5+evj4lJ0vPH+ITsKacdQ9D",
	"EWxAqmA6PNATQPOtaTiRizihCmJVCLhUkDmgizjpsv96cXZ/duICSzO8hnv92Ryttd6c/RLzzcx1dK8d",
	"DIYu+UPCdAH8XcDKW3h/mzTONyk9bzJQwQCN7735oxBwnHMKkLwQMdyvBS9y/YWAjAU1+72F9wvOAPEV",
	"Ugmgai8ye9EmAQFmwUiKZMKLlKAloMKwBhLeMs9vqfOGFzFmVyWZ94ajQ7myWNYQ7ikZgrr8SUNqb/sT",
	"YE7glFwsZ3GAl7OT4ORkOg9eR/FpcDadzaMzuIheg9v0wDBTe3BpEHbTMajQTUIlSin7jOBrnmLKJEr4",
	"5pYpjlaUEUQVoszQMGZFH7lQOF3cskSpXC4mE8JjGWY0FlzylQpjnk2ABYWcYL1/gmNFHyAgVECsuNhO",
	"VgUjOAOmcCoHq0HCN4HigWYdWCl6ejuNz2F1ujwLpvF8FZwQHAX4bDYLomV0Fs3mr8k5OT940xslDs3t",
	"953SeXkaFx+LYvb+MZxB91Jn28AsHQTZIuCC8FZfTgnlDRvyjwupeEb/wPXV23ev33Z373yPUI1rWahB",
	"RBUJpMHFeEgTFtLxQeVSH6sEORTeOrgGLPdqSuacSXCYijiyXd8axLtraO03uqxXD0pdEnLbvqTT4ivH",
	"hSBY4aM13ic3Fsp1YHCIuaLCulzjFBOc04mBHSwLmhIQk4epZS1B/iOlGVU/TKPbIopmZ3y1kqB+iFw+",
	"lOLnID2NDt4vK0TJ0OU3GViN9u6Vrmxa/kKZgjWIAXm7b0i3t80wqRTtWyu6DO6uN2IBWAG5x8pZrzkd",
	"2/K3McPh5c2y3yZvMA1CShdNjuPPeA39+jLnUq0FyC/pU6rLbmQ+5NDX7b27ncOaP7XihluZnWzadsAr",
	"IOhnrNA7pkDkgkpAHygrvqLvrn5+9+F7dBE6U/Uw9o9Fzp4VzEG/g+fugETHB9uBHhyaf//24zc1F926",
	"5AOVSlcmDzilBL3nfJ0CqrYjxZGhUtYpORcKCNLuXyhAv3BSVS+aS3jL3uE4QVZxKCukQjFnClOGMJI5",
	"xHRFQVR1UMkEaflC9Jvhv+Iiw0oiLGBxyxAK0KtCglg8QoZpSsnu1QK9Ycj8hTAhAqREKsEKCcgFSK3M",
	"hlesSaCeUCH6FxeoNLuPXuGUxvBj+beukF6FJWcJ4oHG8MaeeyIGy7okMcY72wZcJSACnOc/4jyXOVfh",
	"ujxUnWlDMkXPU7VRym/OhhZXTwUko0w6dUB4hilbPNp/NcObBNB7dF1QBch+Rd/lgmZYbL8fMk9Ty1Ab",
	"XFtSWutjVZ7ta2RtsBoIiAv0aoAJocsVYlzV/kT8g85JpT2hPZkYV0WYbS21SsvdSvaTZ9xu4Bu6JO16",
	"xbEm9HzPGm+obB1NrJrbH1++168DyfNVyb6moOmXPVBrTCBjYAQzFSwFpiSYR/PT6fxgtG2R8w8V3T/f",
	"3Hx8JwQXruyhME3dqqQqhcMlpt3mV5Tu2vx0DB3yBL10fOhv0B+yb0lYQ+gU586BRzUPcJcg9RjCuWwb",
	"0fumItkrQCcpOQcfNZYO5wGfWrAxv2xKeGBFZly+iGOQukZbYZpaFjkwogXxPVOY2p+Wlf0tYE2lAiPt",
	"XbuNbaiNqeS4JqJzuwa3tOkfPtrSbChodfUcY5BMB1zn2gMIWVZJR1UyFa3mZAvTc/U0lYgv0MZUhe1I",
	"G2P/ajemYRiG39Lc7Gc4PZrjX6flcYC5An2N9C1xzA1bS/tlbra6eFz3eoxedIsVfTDdTvAZtoMMJSEW",
	"oMyS79m60lt4OZZywwVx2X+JJQSFSLukEqXyxWQSExYKIAm2UzTngIVJuk56E3wlCqj3LjlPATO9mYs1",
	"ZmW31jkwi06i+ezEH9jTlh4ghhDbvVgoEpm1kB50uw4Qv6/VDtOWilrSuizXzQUD0/GmZcFs++vKW3w6",
	"MNkeeVDZ+fvPjfVKh86NT8l3d3UIOyb435gR/6CYsHmvUsO4BscyYEuBnMFTFFhlo2MVd+T+4czVKOqp",
	"mVoUjJXpeKTm/fNKL7H4A+3X2r6pnnsqsHij96/jXF8MLaET2G9Nwu1a6ehM3CTenYkjKz5s1K/LVrJs",
	"sVK8lWV7Y1ITqqesOnjHUKZsW0F4b3IcJ4BmYaRrIB0/vOqJYLPZhNgsh1ysJ+VZOflw+fbdL9fvglkY",
	"hYnK0latbKuzKiVWTW6rgFh40zAyUS4HhnPqLbx5GIVTbWusEqOcSbsilJPHdr7c6Q1rUNbVQZh4dEm8",
	"hfceVPdtTFMUOAMFutb+1NdamypacYE2CY0TpDhKOf+MihzhB0xTvEwB4R5hykzCUIlXjYv68+3GhjbM",
	"Wzd02fvOvFyYSspIP4sim7yZApu+cZ6nNDaSTn6X1msaesc++2m33/k9JWCUllOeEWERZkR30VQgLCWP",
	"KdadtPUuVV+muujUprEjnBEirZMtllr9GK3pAzDUUaQmXo2MzS3iNml0pSg3oKr17DpGOZK9LBfL2/BP",
	"TrbPpufeo45D0bY5NDOOUgUcLQGVyMnAY3YDr5g+P9qyfnfArTSaYImkwkIB0Zf25Bl9s9sjOzBoN6pw",
	"lEZDVKIMp7pm04A6ntd1grbjyH0xoxrYHwoXGf6KcGbGknxV4ZI+IrDCRarQNIqqwPClANM0lZHB9AKe",
	"IwS06vERj5Yo175i+4eG1xgnu28/q5cMN4PXrr0Rp7bOMIJgFPM0hdjEZr5CuYAHygvZ9wdpIod2lJSv",
	"1zowMTNL7Jp/8lj+uiTt9NHFZWsAEwlZeUWruOOPes11VTjsdZ1L0hIXlYwUR2tjK0cuqeH+3ySSrrx7",
	"AoZsRhpdk+7RrzEW6b+KjF3Y7vPJC8rcZXRk8iS9Q87cuGf3pKyLwgrrmBp+tfv+LctyY6iELlgBqhBM",
	"IpVQiQiPi0wryA2wxIA0hvrFpGoDFV7LehxwZzC3HxDH8FZToyeVZa1irOKhb/xI+PvTJdgg/LarlyeC",
	"6E0zvwFEzawCMM5UQvm/x76BXTfBVcxfKsHVwv2lEtxg9Lk3KtTXYme2TQRgW3OO3ZFmcvaCMjRMHOBF",
	"a7EdGWz0KP8/X3vLpNXJOvNqFVOq985qvyOp/lYvvZjwFQun3foQ3cFxuKuev7ni2ZWdW6CUxzhNt3WT",
	"7Rwge8OL8qTzurW+2/0vAAD//8Cm6Qx/LAAA",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
