/*
 * Osbuild-installer backend service
 *
 * Service that relays image build requests
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// DefaultApiService is a service that implents the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API. 
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// OsbuildInstallerViewsV1GetVersion - get the service version
func (s *DefaultApiService) OsbuildInstallerViewsV1GetVersion() (interface{}, error) {
	// TODO - update OsbuildInstallerViewsV1GetVersion with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'OsbuildInstallerViewsV1GetVersion' not implemented")
}
