/*
 * Osbuild-installer backend service
 *
 * Service that relays image build requests
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Version struct {

	Version string `json:"version"`
}
